**Marketing A/B Testing**

**About :** It is an Synthetic Dataset of 588101 rows x 7 columns containing the data regarding the company.

In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Marketing A-B Testing/marketing_AB.csv')
display(df.head())

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14

**Basic Understanding regarding the dataset**

**Display the top 5 rows in the dataset**

In [ ]:
df.head()

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20
1,1,1119715,ad,False,93,Tuesday,22
2,2,1144181,ad,False,21,Tuesday,18
3,3,1435133,ad,False,355,Tuesday,10
4,4,1015700,ad,False,276,Friday,14

**Display the last 5 rows in the dataset**

In [ ]:
df.tail()

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
588096,588096,1278437,ad,False,1,Tuesday,23
588097,588097,1327975,ad,False,1,Tuesday,23
588098,588098,1038442,ad,False,3,Tuesday,23
588099,588099,1496395,ad,False,1,Tuesday,23
588100,588100,1237779,ad,False,1,Tuesday,23

**Read the data from 21 to 30**

In [ ]:
df.head(31).tail(10)

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
21,21,1478526,ad,False,389,Saturday,19
22,22,1436823,ad,False,136,Sunday,16
23,23,1274572,ad,False,47,Saturday,21
24,24,1441220,ad,False,264,Saturday,3
25,25,1025687,ad,False,87,Tuesday,23
26,26,1451900,ad,False,46,Tuesday,20
27,27,1098821,ad,False,3,Tuesday,19
28,28,1333281,ad,False,114,Monday,23
29,29,1238323,ad,False,175,Thursday,21
30,30,1034350,ad,False,87,Tuesday,19

In [ ]:
help(df.iloc())

Help on _iLocIndexer in module pandas.core.indexing object:

class _iLocIndexer(_LocationIndexer)
 |  Purely integer-location based indexing for selection by position.
 |
 |  .. deprecated:: 2.2.0
 |
 |     Returning a tuple from a callable is deprecated.
 |
 |  ``.iloc[]`` is primarily integer position based (from ``0`` to
 |  ``length-1`` of the axis), but may also be used with a boolean
 |  array.
 |
 |  Allowed inputs are:
 |
 |  - An integer, e.g. ``5``.
 |  - A list or array of integers, e.g. ``[4, 3, 0]``.
 |  - A slice object with ints, e.g. ``1:7``.
 |  - A boolean array.
 |  - A ``callable`` function with one argument (the calling Series or
 |    DataFrame) and that returns valid output for indexing (one of the above).
 |    This is useful in method chains, when you don't have a reference to the
 |    calling object, but would like to base your selection on
 |    some value.
 |  - A tuple of row and column indexes. The tuple elements consist of one of the
 |    above inputs, e.g. ``(0, 1)``.
 |
 |  ``.iloc`` will raise ``IndexError`` if a requested indexer is
 |  out-of-bounds, except *slice* indexers which allow out-of-bounds
 |  indexing (this conforms with python/numpy *slice* semantics).
 |
 |  See more at :ref:`Selection by Position <indexing.integer>`.
 |
 |  See Also
 |  --------
 |  DataFrame.iat : Fast integer location scalar accessor.
 |  DataFrame.loc : Purely label-location based indexer for selection by label.
 |  Series.iloc : Purely integer-location based indexing for
 |                 selection by position.
 |
 |  Examples
 |  --------
 |  >>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
 |  ...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
 |  ...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
 |  >>> df = pd.DataFrame(mydict)
 |  >>> df
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  **Indexing just the rows**
 |
 |  With a scalar integer.
 |
 |  >>> type(df.iloc[0])
 |  <class 'pandas.core.series.Series'>
 |  >>> df.iloc[0]
 |  a    1
 |  b    2
 |  c    3
 |  d    4
 |  Name: 0, dtype: int64
 |
 |  With a list of integers.
 |
 |  >>> df.iloc[[0]]
 |     a  b  c  d
 |  0  1  2  3  4
 |  >>> type(df.iloc[[0]])
 |  <class 'pandas.core.frame.DataFrame'>
 |
 |  >>> df.iloc[[0, 1]]
 |       a    b    c    d
 |  0    1    2    3    4
 |  1  100  200  300  400
 |
 |  With a `slice` object.
 |
 |  >>> df.iloc[:3]
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  With a boolean mask the same length as the index.
 |
 |  >>> df.iloc[[True, False, True]]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  With a callable, useful in method chains. The `x` passed
 |  to the ``lambda`` is the DataFrame being sliced. This selects
 |  the rows whose index label even.
 |
 |  >>> df.iloc[lambda x: x.index % 2 == 0]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  **Indexing both axes**
 |
 |  You can mix the indexer types for the index and columns. Use ``:`` to
 |  select the entire axis.
 |
 |  With scalar integers.
 |
 |  >>> df.iloc[0, 1]
 |  2
 |
 |  With lists of integers.
 |
 |  >>> df.iloc[[0, 2], [1, 3]]
 |        b     d
 |  0     2     4
 |  2  2000  4000
 |
 |  With `slice` objects.
 |
 |  >>> df.iloc[1:3, 0:3]
 |        a     b     c
 |  1   100   200   300
 |  2  1000  2000  3000
 |
 |  With a boolean array whose length matches the columns.
 |
 |  >>> df.iloc[:, [True, False, True, False]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  With a callable function that expects the Series or DataFrame.
 |
 |  >>> df.iloc[:, lambda df: [0, 2]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  Method resolution order:
 |      _iLocIndexer
 |      _LocationIndexer
 |      pandas._libs.indexing.NDFrameIndexerBase
 |      builtins.object
 |
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _LocationIndexer:
 |
 |  __call__(self, axis: 'Axis | None' = None) -> 'Self'
 |      Call self as a function.
 |
 |  __getitem__(self, key)
 |
 |  __setitem__(self, key, value) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from _LocationIndexer:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from _LocationIndexer:
 |
 |  axis = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __reduce__ = __reduce_cython__(...)
 |
 |  __reduce_cython__(self)
 |
 |  __setstate__ = __setstate_cython__(...)
 |
 |  __setstate_cython__(self, __pyx_state)
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  __new__(*args, **kwargs) class method of pandas._libs.indexing.NDFrameIndexerBase
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  name
 |
 |  ndim
 |
 |  obj

**Display first Row**

In [ ]:
df.iloc[[0]]

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
0,0,1069124,ad,False,130,Monday,20

**Display Rows from 21 to 30**

In [ ]:
df.iloc[21:31]

,Unnamed: 0,user id,test group,converted,total ads,most ads day,most ads hour
21,21,1478526,ad,False,389,Saturday,19
22,22,1436823,ad,False,136,Sunday,16
23,23,1274572,ad,False,47,Saturday,21
24,24,1441220,ad,False,264,Saturday,3
25,25,1025687,ad,False,87,Tuesday,23
26,26,1451900,ad,False,46,Tuesday,20
27,27,1098821,ad,False,3,Tuesday,19
28,28,1333281,ad,False,114,Monday,23
29,29,1238323,ad,False,175,Thursday,21
30,30,1034350,ad,False,87,Tuesday,19

In [ ]:
df.iloc[[0,2], [1,2,3,4]]

   user id test group  converted  total ads
0  1069124         ad      False        130
2  1144181         ad      False         21

**How many rows and columns are present in this dataset?**

In [ ]:
df.shape

(588101, 7)

**Find the columns and their datatypes**

In [ ]:
df.columns

Index(['Unnamed: 0', 'user id', 'test group', 'converted', 'total ads',
       'most ads day', 'most ads hour'],
      dtype='object')

**Find the data types of the dataset**

In [ ]:
df.dtypes

Unnamed: 0        int64
user id           int64
test group       object
converted          bool
total ads         int64
most ads day     object
most ads hour     int64
dtype: object

**Overview of the dataset**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Unnamed: 0     588101 non-null  int64
 1   user id        588101 non-null  int64
 2   test group     588101 non-null  object
 3   converted      588101 non-null  bool
 4   total ads      588101 non-null  int64
 5   most ads day   588101 non-null  object
 6   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(4), object(2)
memory usage: 27.5+ MB

**Tell me about null values based on each columns**

In [ ]:
df.isnull().sum()

Unnamed: 0       0
user id          0
test group       0
converted        0
total ads        0
most ads day     0
most ads hour    0
dtype: int64

**Find the duplicate rows**

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

          Unnamed: 0       user id      total ads  most ads hour
count  588101.000000  5.881010e+05  588101.000000  588101.000000
mean   294050.000000  1.310692e+06      24.820876      14.469061
std    169770.279667  2.022260e+05      43.715181       4.834634
min         0.000000  9.000000e+05       1.000000       0.000000
25%    147025.000000  1.143190e+06       4.000000      11.000000
50%    294050.000000  1.313725e+06      13.000000      14.000000
75%    441075.000000  1.484088e+06      27.000000      18.000000
max    588100.000000  1.654483e+06    2065.000000      23.000000

**Count :** Number of non-null values

**mean :** Avergae value

**std :** Standard deviation (spread of data)

**min :** Smallest Value

**25% :** First Quartile (Q1)

**50% :** Meadian

**75% :** Third Quatile

**max :** Largest Value

**Data Cleaning - Unnamed**

**Explanation** : Since that Unnamed column is just giving row numbers, it is completely useless for our analysis

In [ ]:
df = df.drop(columns=['Unnamed: 0'])

**Verifying the existing columns**

In [ ]:
print(df.columns.tolist())

['user id', 'test group', 'converted', 'total ads', 'most ads day', 'most ads hour']

In [ ]:
df.describe()

            user id      total ads  most ads hour
count  5.881010e+05  588101.000000  588101.000000
mean   1.310692e+06      24.820876      14.469061
std    2.022260e+05      43.715181       4.834634
min    9.000000e+05       1.000000       0.000000
25%    1.143190e+06       4.000000      11.000000
50%    1.313725e+06      13.000000      14.000000
75%    1.484088e+06      27.000000      18.000000
max    1.654483e+06    2065.000000      23.000000

**Data Cleaning - Userid**

**Checking the null values in these columns**

In [ ]:
print("user id :", df['user id'].isnull().sum())

user id : 0

**Checking Unique Values in the User id Column**

In [ ]:
print(df['user id'].unique())

[1069124 1119715 1144181 ... 1038442 1496395 1237779]

**Find the duplicate rows in these columns**

In [ ]:
print("User ID duplicates:", df['user id'].duplicated().sum())

User ID duplicates: 0

**Data Cleaning - Test group**

**Checking the null values in these columns**

In [ ]:
print("test group :", df['test group'].isnull().sum())

test group : 0

**Checking Unique Values in the test group Column**

In [ ]:
print(df['test group'].unique())

['ad' 'psa']

**Data Cleaning - Converted**

**Checking the null values in these columns**

In [ ]:
print("converted :", df['converted'].isnull().sum())

converted : 0

**Checking Unique Values in the Converted Column**

In [ ]:
print(df['converted'].unique())

[False  True]

**Data Cleaning - total ads**

**Checking the null values in these columns**

In [ ]:
print("total ads :", df['total ads'].isnull().sum())

total ads : 0

**Checking Unique Values in the total ads Column**

In [ ]:
print(df['total ads'].unique())

[ 130   93   21  355  276  734  264   17  142  209   47   61   40   20
    9   64   26  248   73  281  389  136   87   46    3  114  175  119
  313   89  364   24  112   49   27  274   45  177   90  265   71   31
  588   56  108  103  239   63   66  111   74   14  258 1057  137  131
  124   13   37  738  199  211   98   19  127   18  126  197   77   60
   95   97   22  117   41   57  593   28   85   53   43  133   33 1328
    7    6   62  247  464   99  233  139  407  323   76  395  166   34
  246  653  122   32  386   44  138  109   39  159   30   59  421  446
  555  105  128  310  163   10  290  164   79  312   16  161  505  640
  118  266  456   80  100  983   36    1    5  463  720   52  442  334
 1056  270  240  194  271  489  115  180  241   15  154  120   29  107
  176    8  146  121   50   69  297   35   78  170  214   81    2   38
  681  733   23  157  153  135   88  167    4   58  195  318   48   83
   96  392  371   91   68  427  516  249   54   11   25  171   55  403
  140  455  222   82  168  225  633  116  188  423   70  110  311  174
  208   92  172  657  260  191  173  245  150   84  134  526  607   75
  302   94  294  288   42  123  179  160   51  190  221  216  347  102
   65 1632  106  125  317  206  350  202  148  145  525  445  309  186
  486  380  178  321  205   86  149  413   67  587  351  147  144  470
  387  335  235  306  230  535  181  401  394  568  155  326  308  617
   12  655  158  375  237  104  218  215  345  141  253   72  193  700
  400 1015  360 1128  292  151  224  779  213  304  220  207  261  536
  515  184  152  232  490  228  532  790  203  285  234  429  325  231
  101  393  129  352  182  332  307  378  226  642  385  187  452  132
  504  143  198  243  269  447  287  468  338  185  728  169  113  991
  514  554  571  192  298  242  542  698  196 1173  183  466  156  257
  189  305  438  212  461  286  252  521  162  354  353  857  315  272
  284  262  374  283  675  566  582  399  411  368  404  280  487  602
  443  950  362  523  301  259  165  376  219  679  358 1021  251  282
  329 1135  383  761  481  291  594  688  328  238  327  441  430  434
  300  416  357  275  558  448  499  279  546  359  426  817  433  610
 1010  343  341  420  474  622  654  348  459  507  250  388  592  200
  322  227  802  295  467  217  806  414  599  612  316  415  631  256
  606  278  320 1011  236  223  739  444  396  758 1020  370  947  277
  485  412  436  477  273  541  244  825  613  263  204  342  372  805
  356  267  820  852  408  809  268  324  379  527  336  503  465  451
  432  480  719  771  629  473  254  552  484  603  210  373  417  425
  418  584  391  479  938  361  424  497 1129  687  303  369  569  628
  563  330  201  670  564  586  842  337  339  314  630  491  731  340
  382  296  492  502  601  437  509  346  494  804  501  540  595  578
  920  493  794  293  518  440  652  598  724  344  764 1680  641  365
 1100  410  907  333  255  506  331  845  435  742  496  667  705  689
  457  591  495  551  608  319  367  402  619  299  647  522 1229  562
 1398  229  377  634  478  703  662  556  462  483  431  405  710  636
  775  539  557  574  714  609  524  449  476  544  545  512  428  678
  406  797  639  702 1016  453  482  575  289  745  381  397  621  909
  585  580  409 1491  727  926  711  815  419 1302  735 1035  517  716
  789 1014  572  363 1414  643  627  645  753  533  887  384  704  709
  460  854 1267  663  488  439  547  840  472  510  863  520  366  781
  769  511  744  398  743  646  349  865  538  422  660 1003  615  549
  894  500  713  723  915 1321 2065 1354  722  561 1101  519  560  471
 1196  665  828  573  961  799  651  454  597  648  934  620  690 1778
  616  637  624  390  530  772  604  656  760  786  469  649  925  798
  548  611  841  625  691  888  932  695  785 1146  891  883  581  911
  565  638  550  583  800  664 1391  699  827  791  579  955  901  570
  763  672  812  669  788  596  458  986 1232 1032  908  873  923  567
  730  498  792  543  759  885  858  869  508  475  450  659  559  712
  684  904  680  706  921  673  952  808  729]

**Data Cleaning - most ads day**

**Checking the null values in these columns**

In [ ]:
print("most ads day :", df['most ads day'].isnull().sum())

most ads day : 0

**Checking Unique Values in the most ads day Column**

In [ ]:
print(df['most ads day'].unique())

['Monday' 'Tuesday' 'Friday' 'Saturday' 'Wednesday' 'Sunday' 'Thursday']

**Data Cleaning - most ads hour**

**Checking the null values in these columns**

In [ ]:
print("most ads hour :", df['most ads hour'].isnull().sum())

most ads hour : 0

**Checking Unique Values in the most ads hour Column**

In [ ]:
print(df['most ads hour'].unique())

[20 22 18 10 14 13 19 11 12 16 21  3 23  4  8  0  2 15  1  6 17  7  9  5]

**Final Cleaned Dataset**

In [ ]:
print(df.shape)
print(df.head())

(588101, 6)
   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

In [ ]:
df.to_csv('cleaned_marketing.csv', index=False)

**Cleaning Notes** <br>
1.The dataset contained no duplicate records. <br>
2.No missing values were present in any column.<br>
3.The redundant Unnamed: 0 (index) column was dropped from the cleaned dataset. <br>
4.Data types across all columns were verified and confirmed to be correct.<br>
5.The categorical columns (test group, most ads day) were reviewed and kept as is.<br>
6.The numeric columns (user id, total ads, most ads hour) were checked and validated.<br>
7.The boolean values in the converted column remained intact and unchanged.